# .github/workflows/release.yml

name: Go Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1' 

      # Step 3: Tidy the go.mod file to ensure all dependencies are clean.
      - name: Tidy modules
        run: go mod tidy

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o leveldb-parser-go-linux-amd64

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o leveldb-parser-go-windows-amd64.exe

      - name: Build for macOS (ARM)
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o leveldb-parser-go-darwin-arm64

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            leveldb-parser-go-linux-amd64
            leveldb-parser-go-windows-amd64.exe
            leveldb-parser-go-darwin-arm64
          generate_release_notes: true

